### ISSUE TITLE
False Positive | NoslowDown Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#10]
How do you trigger the false positive? Describe it here
if you have essentials plugin do /speed 2 or more and then block your sword while moving forward you will false noslowdown

Verbose Message
There In The Video

Cardinal Version: 0.9956
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/xvpya

**Comment by Clientastisch** [comment]
Are you sure, that it's not fault of speed or block animation ? Cause I couln't reproduce it myself and my movement wasn't so fast

**Comment by coolpvpv1** [comment]
> Are you sure, that it's not fault of speed or block animation ? Cause I couln't reproduce it myself and my movement wasn't so fast

hmm try doing /speed 10

**Comment by Clientastisch** [comment]
I've tested this one with different clients and legit clients. Every Time I had sprint enabled this occurred. I guess it's just a client bug because I couldn't trigger it without client. Probably It's impossible to sprint with such a high walkSpeed, wouldn't be the first time, that spigot is stupid
