### ISSUE TITLE
Bug Report | Server Crash

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#101]
**What type of bug you want to report? Describe it here**
When I try to import a setting, it crashes the server

**When the bug occurrs?**
When I try to import a setting

**Cardinal Version:** Latest
**Spigot Version:** Paper 1.8.8 (Latest release)

**Attached Files**
Settings.setting https://hatebin.com/ujevucmsbm

**Comment by Clientastisch** [comment]
Idk, does work in version 0.9983
