### ISSUE TITLE
Bug Report | Chunk Load

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#102]
**What type of bug you want to report? Describe it here**
The world doesn't load and it sends an error to the console. Then it kicks me

**When the bug occurs?**
Sometimes when I join the server

**Cardinal Version:** Latest
**Spigot Version:** Paper 1.8.8 (Latest release)

**Attached Files**
https://hatebin.com/qqkkrvwnmj

**Comment by Clientastisch** [comment]
Turn off Hybrid mode

**Comment by Clientastisch** [comment]
That should do it

**Comment by Jakaboii** [comment]
What does Hybrid mode do?

**Comment by Clientastisch** [comment]
async world loading

**Comment by Clientastisch** [comment]
But I guess I'll remove it

**Comment by Jakaboii** [comment]
Ooh, OK
I'll try without Hybrid mode

**Comment by Jakaboii** [comment]
Yup, it worked without Hybrid mode
