### ISSUE TITLE
False Positive | Crouching with Item

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#103]
**How do you trigger the false positive? Describe it here**
You crouch repeatedly with an item in your hand

**Verbose Message**
https://hatebin.com/pignnuuhqi

**Cardinal Version:** Latest
**Spigot Version:** Paper 1.8.8 (Latest)

**Attached Video  (Required)**
https://streamable.com/vkved

**Comment by Clientastisch** [comment]
Just with an item ? Or also without ?

**Comment by Jakaboii** [comment]
Just with an item, i demonstrated without one then with one

**Comment by Clientastisch** [comment]
could you try wihout PvPLounge ?

**Comment by Jakaboii** [comment]
OK, 1 sec

**Comment by Jakaboii** [comment]
It's fine without PvPLounge

**Comment by Clientastisch** [comment]
Thought so...

**Comment by Jakaboii** [comment]
Is there a way to fix that in future updates? Because I know CAC has some issues with PvPLounge

**Comment by Clientastisch** [comment]
Well... 
I think up something

**Comment by Jakaboii** [comment]
OK, thanks

**Comment by Clientastisch** [comment]
But we should note that PvPLounge is not as legit as expected
