### ISSUE TITLE
Bug Report | CAC Ban

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#104]
**What type of bug you want to report? Describe it here**
When I use hacks and get banned (perm banned or temp banned) I just just rejoin

**When the bug occurs?**
When I get banned & rejoin

**Cardinal Version:** Latest
**Spigot Version:** Paper 1.8.8 (Latest release)

**Attached Files**
https://streamable.com/weu07

**Comment by Clientastisch** [comment]
I've told that like a thousand times by now. The Anticheat stores bans in a database, you have to enter a valid database or else it doesn't store them

**Comment by Jakaboii** [comment]
I do have it in a valid database
everything worked before

**Comment by Jakaboii** [comment]
@Clientastisch (@ing you just in case you don't get notifications on closed issues)

**Comment by Jakaboii** [comment]
OK I fixed it
I think there was too much requests to the database, so I just made another one specifically for CAC
