### ISSUE TITLE
Bug Report | CAC Ban

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#105]
**What type of bug you want to report? Describe it here**
When I hack, I don't get banned
CAC is connected to a working database, anytime I get banned I can just rejoin
This never happened before and I don't know why it just started a few days ago

**When the bug occurrs?**
When I get banned

**Cardinal Version:** Latest
**Spigot Version:** Paper 1.8.8 (Latest Release)

**Attached Files**
https://streamable.com/weu07

**Comment by Clientastisch** [comment]
Well if it started a few days ago, it's not the fault of CAC. There were no updates the last couple of days

**Comment by Clientastisch** [comment]
I tested the ban system and it's all right...
