### ISSUE TITLE
False Positive | KillAura Type A

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#106]
**How do you trigger the false positive? Describe it here**
I was just butterfly clicking an NPC while jumping, and I got flagged for KillAura Type A, then banned
I wasn't even butterfly clicking that fast

**Verbose Message**
CAC: Jakaboii tried KillAura Type A: 1
CAC: Jakaboii tried KillAura Type A: 2
CAC: Jakaboii tried KillAura Type A: 3
Jakaboii tried KillAura Type A: 4
Jakaboii tried KillAura Type A: 5

**Cardinal Version:** Latest
**Spigot Version:** Paper 1.8.8 (Latest Release)

**Attached Video (Required)**
https://streamable.com/4jjuf

**Comment by Clientastisch** [comment]
Did you use PvPLounge ?

**Comment by Jakaboii** [comment]
No

**Comment by Clientastisch** [comment]
should be fixed in version 0.9983
