### ISSUE TITLE
Bug Report |  Disabling elytra /  Two same options

### ISSUE THREAD

**Issue by MisterLolxd2** [Clientastisch/Cardinal-Anticheat#108]
**What type of bug you want to report? Describe it here**

1. Disabling elytra, 2. Two same options. 

**When the bug occurrs?**

1. When the cardinal is turned on, the elytra does not work.
2. When we use the command [/CAC CONFIG], on the second page you can see two the same PacketDecoder Type E options.

**Cardinal Version: 0.9983
**Spigot Version: PaperSpigot 1.12.2

**Attached Files**
---

**Comment by Clientastisch** [comment]
Thank you for your report, it will be fixed in version 0.9984.
