### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#109]
**What type of bug you want to report? Describe it here**
going into /cac gui going to the bans second page and if you find packetdecoder type e in the middleish of the gui theres two of those options on it

**When the bug occurrs?**
going into /cac gui going to the bans second page and if you find packetdecoder type e in the middleish of the gui theres two of those options on it

**Cardinal Version: 0.9983
**Spigot Version: 1.8.8

**Attached Files**
cac

**Comment by Clientastisch** [comment]
Already saw that. I just failed to rename the secound E into F
Thank you for your report though :) This will be fixed in version 0.9984
