### ISSUE TITLE
False Positive | AimAssist Type B

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#11]
How do you trigger the false positive? Describe it here
when you just aim to the left or right not to fastly when a player gets kb it falses alot

Verbose Message
In The Video

Cardinal Version: 0.9956
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/9a0bd

**Comment by Clientastisch** [comment]
I've changed my whole AimAssist Type B code, It'll now detect a few killauras but it's only experimental so far. It'll be available with version 0.9957
