### ISSUE TITLE
Bug Report | Plugin Disable

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#110]
**What type of bug you want to report? Describe it here**
The plugin automatically disables by itself

**When the bug occurrs?**
Randomly (I think a player has to be online)

**Cardinal Version:** Latest
**Spigot Version:** Paper 1.8.8 (Latest Release)

**Attached Files**
https://hastebin.com/ukapecacof.shell

**Comment by Clientastisch** [comment]
Hastebin link is emtpy

**Comment by Jakaboii** [comment]
it just had this message
`[13:54:50 INFO]: Jakaboii lost connection: Disconnected 
[14:02:12 INFO]: [CAC] Disabling CAC v0.9983
[14:02:12 INFO]: CAC: Disabling CAC...
[14:02:12 INFO]: CAC: This could take a while
[14:02:12 INFO]: CAC: ConsoleLog v1.0 has successfully been unloaded'

**Comment by Jakaboii** [comment]
If you can, can you release a hotfix?

I need the AntiCheat before the 25th (tomorrow)

**Comment by Clientastisch** [comment]
Doesn't look like an issue that has to be fixed via an update. I try to fix that today evening and also make the pvplounge addon

**Comment by Jakaboii** [comment]
OK, thanks a lot!

**Comment by Clientastisch** [comment]
Should be fixed now
