### ISSUE TITLE
Bug Report | Cardinal kick players

### ISSUE THREAD

**Issue by MisterLolxd2** [Clientastisch/Cardinal-Anticheat#111]
**What type of bug you want to report? Describe it here**

1. Cardinal kick players.

**When the bug occurrs?**

1. Cardinal ejects players from the server immediately after connecting, because the reason is an internal connection, etc. [in 0.9983 in it was normal]

**Cardinal Version: 0.9984
**Spigot Version: PaperSpigot 1.12.2

**Attached Files**
[18:28:38] [Server thread/INFO]: [CAC] Enabling CAC v0.9984
[18:28:41] [Server thread/INFO]: 

                           .o88b.  .d8b.   .o88b.
                          d8P  Y8 d8' `8b d8P  Y8
                          8P      88ooo88 8P     
                          8b      88   88 8b     
                          Y8b  d8 88   88 Y8b  d8
                           `Y88P' YP   YP  `Y88P'
                                  
                                  
 
 
 _              _____ _ _            _            _   _          _     
| |            / ____| (_)          | |          | | (_)        | |    
| |__  _   _  | |    | |_  ___ _ __ | |_ __ _ ___| |_ _ ___  ___| |__  
| '_ \| | | | | |    | | |/ _ \ '_ \| __/ _` / __| __| / __|/ __| '_ \ 
| |_) | |_| | | |____| | |  __/ | | | || (_| \__ \ |_| \__ \ (__| | | |
|_.__/ \__, |  \_____|_|_|\___|_| |_|\__\__,_|___/\__|_|___/\___|_| |_|
        __/ |                                                          
       |___/                                                           
 
 
[18:28:30] [Server thread/INFO]: [CAC] Loading CAC v0.9984
[18:28:41] [Server thread/INFO]: Detected server version VERSION_1_12
[18:28:41] [Server thread/INFO]: Loaded Checks: 94
[18:28:41] [Server thread/INFO]: Using CPU: 3 / 8
[18:28:41] [Server thread/INFO]: Resource: Loaded
[18:28:41] [Server thread/INFO]: Version: Outdated
[18:28:41] [Server thread/INFO]: Replay: Disabled
[18:28:41] [pool-8-thread-1/INFO]: Connection: Failed
[18:28:41] [pool-8-thread-2/INFO]: CAC: Successfully updated...
[18:28:41] [pool-8-thread-2/INFO]: CAC: Reload to see changes

**Comment by Clientastisch** [comment]
Restart the server, that's not an Cardinal issue

**Comment by MisterLolxd2** [comment]
I restarted the server several times when the new version of caridnal was turned on, and after turning off caridnal everything worked normally.

**Comment by Clientastisch** [comment]
I don't see anything wrong there
Send me more of the log

**Comment by MisterLolxd2** [comment]
Everything I sent above was about the cardinal, there is nothing else. By the way, I downloaded the latest version 0.9995 and the error still occurs

and this: 
[18:48:50] [Server thread/INFO]: MyNick lost connection: Disconnected
[18:48:50] [Craft Scheduler Thread - 5/INFO]: CAC: Couldn't connect properly to sql

**Comment by Clientastisch** [comment]
Oh you mean that

**Comment by Clientastisch** [comment]
The anticheat isn't connected to a database

**Comment by Clientastisch** [comment]
But that can't be the reason why a player get's kicked while connecting

**Comment by Clientastisch** [comment]
Or is that for hacking ?

**Comment by MisterLolxd2** [comment]
Carindal was never hooked up to sql and I acted normally, and only now "went crazy"
Carindal eject without reason in logs or consoles has nothing. However, it seems that the connection is crashed by the cardinal. Therefore, the reason is internal expression / connection ...

**Comment by Clientastisch** [comment]
I was stupid a forget a if statement. Download the newest build again

**Comment by Clientastisch** [comment]
And the connection is sure not crashes becasue of Cardinal. This message will be printed for banning. However, if you are using PvPLounge remember to download the addon. PvPLounge is not considerated as legit

**Comment by MisterLolxd2** [comment]
I never use the addon. Despite downloading the new Carindal, the error still occurs.
 [19:13:14 INFO]: MyNick lost connection: Disconnected
 [19:13:14 INFO]: CAC: Couldn't connect properly to sql
 [19:13:14 INFO]: CAC: Couldn't connect properly to sql
 [19:13:14 INFO]: CAC: Couldn't connect properly to sql
 [19:13:14 INFO]: CAC: Couldn't connect properly to sql
 [19:13:14 INFO]: CAC: Couldn't connect properly to sql
 [19:13:14 INFO]: CAC: Couldn't connect properly to sql
 [19:13:14 INFO]: CAC: Couldn't connect properly to sql
 [19:13:14 INFO]: CAC: Couldn't connect properly to sql
 [19:13:14 INFO]: CAC: Couldn't connect properly to sql

**Comment by Clientastisch** [comment]
is the Banmanager disabled in the Config ?

**Comment by Clientastisch** [comment]
Are you using PvPLounge ?

**Comment by MisterLolxd2** [comment]
I tested with banmanger turned on and off and the error continued to occur.
No i dont use PvPLounge.

**Comment by Clientastisch** [comment]
Can you send me a video please ?

**Comment by Clientastisch** [comment]
This issue is, that I tested that in every version up to 1.13 and all was fine

**Comment by MisterLolxd2** [comment]
In the case of recording, it will be rather difficult, but I noticed that after moving forward before kick, there was such a reason:
 [19:25:14 INFO]: CONSOLE issued server command: /kick MyNick PacketDecoder

**Comment by Clientastisch** [comment]
PacketDecoder is an anticrash

**Comment by Clientastisch** [comment]
Put this addon into the addon folder located under plugins/CAC/addons
https://cdn.discordapp.com/attachments/666717737187409924/666726697550217239/ConsoleLog.jar

**Comment by Clientastisch** [comment]
This prints the flag into the console

**Comment by MisterLolxd2** [comment]
I connected cardinal to sql and was banned for: 

PacketDecoder Type G |  
-- | --

**Comment by Clientastisch** [comment]
open the file 'PacketDecoder Type G.yml' and tell me which Value is there

**Comment by Clientastisch** [comment]
It has to be greater than 0

**Comment by MisterLolxd2** [comment]
Info: '######### I DONT TAKE RESPONSIBILITY FOR ANY CONFIGURATION #########'
PacketDecoder Type G:
  enable:
    info: Make this to false to disable this check
    val: true
  delay:
    info: Delay in Millis * 1000
    val: 6.0
  acceptableValue:
    info: This is the value of violations which isn't shown in the chat
    val: 0
  maxValue:
    info: This is the value of violations after the player gets punished
    val: 1
  flagPunishment:
    info: This is the punishment for each flag (SILENT, SETBACK, DAMAGE, VELOCITY,
      SLOT, BLINDNESS, ATTACK_CANCLE, DAMAGE_CANCEL)
    val: NONE
  punishment:
    info: 0 stands for kick, 1 stands for tempban, 2 stands for permaban, 3 for nothing
    val: 2
  banlenght:
    info: The time is in minutes (MAX. 0x7fffffff=2147483647)
    val: 30
Setting:
  Value:
    info: Max amount of EntityAction packets per tick
    val: 20

**Comment by Clientastisch** [comment]
Are you using pure vanilla ?

**Comment by MisterLolxd2** [comment]
As for my version of Minecraft, no, but other people have pure Minecraft and have the same error

Well i add you addon and:
 

[19:34:02 INFO]: CAC: MyNick tried PacketDecoder Type G: 1
 [19:34:02 INFO]: MyNick lost connection: Disconnected
 [19:34:02 INFO]: CONSOLE issued server command: /kick MyNick PacketDecoder

**Comment by Clientastisch** [comment]
Could you try pure vanilla ?

**Comment by MisterLolxd2** [comment]
Ok.

**Comment by Clientastisch** [comment]
If the issue is the same, delete the file `Packet Decoder Type G` and execute /CAC rl

**Comment by MisterLolxd2** [comment]
I tried to include in version 1.12.2 but still get the same error.

**Comment by MisterLolxd2** [comment]
I did it, Cardinal generated a new configuration file for this option, but the error remained.

**Comment by Clientastisch** [comment]
Well...
I'll disable the check and take a closer look later

**Comment by Clientastisch** [comment]
Does that also occurr in 1.8 ?

**Comment by MisterLolxd2** [comment]
Yes.

**Comment by Clientastisch** [comment]
Yes ?

**Comment by Clientastisch** [comment]
I tested that on 1.8 without problems

**Comment by Clientastisch** [comment]
Download this one and try again:
https://www.spigotmc.org/resources/cardinal-anticheat-community-edition-1-8-x.72084/download?version=316219

**Comment by MisterLolxd2** [comment]
I also encountered this error after switching to minecraft version 1.8.

**Comment by MisterLolxd2** [comment]
Now is good.

**Comment by Clientastisch** [comment]
Also for 1.8 ?

**Comment by MisterLolxd2** [comment]
On minecraft 1.8, it also works normally.
