### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by MrYanini** [Clientastisch/Cardinal-Anticheat#112]
**What type of bug you want to report? Describe it here**
Tbh i don't know what happend or what i need to do. I installed the .jar and restarted the server.
then when i typed anything with /cac it replys with 
"An internal error occurred while attempting to perform this command"

**When the bug occurrs?**
always, the .jar file is disabled it says but it isn't

**Cardinal Version:
**Spigot Version:
1.15.2

**Attached Files**

**Comment by Clientastisch** [comment]
This anticheat doesn't support versions higher than 1.13
