### ISSUE TITLE
Bug Report | Man kann sich nicht schlagen

### ISSUE THREAD

**Issue by GemsMC** [Clientastisch/Cardinal-Anticheat#113]
Ich besitze einen BuildFFA Server und benutze das Cardinal Anticheat (cac). Jedoch seitdem ich das Plugin auf meinem Server installiert habe, können sich die Spieler nicht mehr gegenseitig schlagen. Zumindest können sie sich einmal kurz schlagen und dann geht's nicht mehr.

Der Bug erscheint wenn sich Spieler ununterbrochen gegenseitig schlagen.

Cardinal Version: 0.9986
Spigot Version: Spigot 1.8.8

**Attached Files**

Console log:
https://pastebin.com/GWdAYf6e

**Comment by Clientastisch** [comment]
Mach KillAura Type A bitte aus
