### ISSUE TITLE
False Positive | Killaura Type A

### ISSUE THREAD

**Issue by LinsaFTW** [Clientastisch/Cardinal-Anticheat#114]
**How do you trigger the false positive? Describe it here**
Hitting at a standing target while moving around him.

**Verbose Message**
![image](https://user-images.githubusercontent.com/25271111/77207603-9300ba00-6ad8-11ea-8fb5-04dde78edebd.png)

**Cardinal Version: 0.9986
**Spigot Version:
![image](https://user-images.githubusercontent.com/25271111/77207639-aa3fa780-6ad8-11ea-98c3-dadcf23fe354.png)

**Attached Video  (Required)**
[Killaura Type A.zip](https://github.com/Clientastisch/Cardinal-Anticheat/files/4361857/Killaura.Type.A.zip)

**Comment by Clientastisch** [comment]
Somehow, I'm unable to reproduce the false positive.
Further information is required...

**Comment by LinsaFTW** [comment]
> Somehow, I'm unable to reproduce the false positive.
> Further information is required...

What kind of info do you need?
