### ISSUE TITLE
Bug Report | Cannot Disable Permanent Bans

### ISSUE THREAD

**Issue by OFWModz** [Clientastisch/Cardinal-Anticheat#119]
**What type of bug you want to report? Describe it here**
Both left and right clicking in the gui for bans to disable a ban on a check does nothing but warn me I already had it set on.

**When the bug occurrs?**
In the cac gui's bans page.

**Cardinal Version: 0.9988
**Spigot Version: Unknown - Using Latest Mohist Build Which Is A Combi.

Note I am also running tekxit 3 with this, but I doubt it is interfering.

**Comment by Clientastisch** [comment]
If you want to enable kicks for a check you have to go into Kicks and click there on the checks.
If you want to enable tempbans for a check you have to go into Tempbans and click there on the checks.
If you want to enable permabans for a check you have to go into Bans and click there on the checks.

**Comment by OFWModz** [comment]
I did. I wanted to disable the permabans for each check and it wouldn't work, but it disabled when I did it for kicks. This is a bug.

**Comment by Clientastisch** [comment]
1. Execute **/CAC config**
2. Klick on **Kicks**
3. Kick on the check

**Comment by OFWModz** [comment]
I. Did.

Can you read? Toggling kicks works fine, toggling permabans only works to enable them, disabling doesn't work.

**Comment by OFWModz** [comment]
I'm literally a coder / developer, stop speaking to me like I'm a retard.

**Comment by Clientastisch** [comment]
Sure ?
If you toggle sth else permabans are disabled

**Comment by OFWModz** [comment]
No. I open your GUI, I go to the bans area, I see glowstone. Clicking them does nothing and notifies me in chat I already have enabled them. This does not occur in the Kicks menu. 

That is a bug.

**Comment by Clientastisch** [comment]
IT IS NOT

**Comment by Clientastisch** [comment]
You have to select tempbans/kicks instead

**Comment by OFWModz** [comment]
Do I have to show a screenshot? = You very clearly don't know what you are on about.

**Comment by Clientastisch** [comment]
I do know what you mean. 
What makes you think that it's a bug if no exception appears and a chat message tells you that it is already toggled ?

**Comment by OFWModz** [comment]
Doing it in the kick menu toggles it from on; to off.
Bans does not.

Yet you can toggle it in the raw config files.

**Comment by OFWModz** [comment]
![image](https://user-images.githubusercontent.com/36628963/79368479-614c0900-7f47-11ea-80e8-7e2b33ce94a4.png)
![image](https://user-images.githubusercontent.com/36628963/79368484-627d3600-7f47-11ea-967f-c67de875c934.png)

Notice the difference?
The only reason I had bans silent before was manually modifying the configs.

**Comment by Clientastisch** [comment]
I know, that's what I coded

**Comment by OFWModz** [comment]
Then why do they have different statuses but the toggle does nothing? Also what is the point in the submenu then if it has no functionality?

**Comment by Clientastisch** [comment]
I do get your point, but it's not a bug though.
However I changed that in the upcoming version...
