### ISSUE TITLE
False Positive | Fly Type A And Vport Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#12]
How do you trigger the false positive? Describe it here
if you have the gadgetsmenu https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-14-4.10885/ (over 141k downloads) use the gadget menu go to gadgets click fun & games then use diving board gadget and stay on the board where it launchs you up in the air twice then go off it into the water it will false fly type a and then go to fun & games again then use trampoline gadget just go on it you get launched in the air and false vport type a

Verbose Message
Its In The Video

Cardinal Version: 0.9956
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/jjely

**Comment by coolpvpv1** [comment]
also found that parachute gadget falses ymotion and vport to heres a video of that https://streamable.com/foy9c

**Comment by Clientastisch** [comment]
Will be mostly fixed in version 0.9957, I'll keep improving that

**Comment by Clientastisch** [comment]
Thank your for your report, your issue will be solved in version 0.9980
