### ISSUE TITLE
Feature Request | Support for 1.15.X

### ISSUE THREAD

**Issue by xarmeetx** [Clientastisch/Cardinal-Anticheat#121]
What features would you like added? Describe them here
Please add support for 1.15.X versions. You'll get a lot more users.

**Comment by Clientastisch** [comment]
Cardinal Anticheat once had 1.13 -1.15 but the performance loss was unacceptable and 1.13 - 1.15 are already incredible instable builds. First of all, I don't recommend at all to use any versions higher than 1.12. Secondly, Cardinal Anticheat is an anticheat made and developed for 1.8

**Comment by xarmeetx** [comment]
@Clientastisch could you please send me the 1.15 support jar?
I'd like to test it out, since my server works on 1.15
