### ISSUE TITLE
False Positive | 

### ISSUE THREAD

**Issue by PlesCZ** [Clientastisch/Cardinal-Anticheat#124]
How do you trigger the false positive? Describe it here
I couldn't record it, but it's similar .. Just Kokos55545 got a ban even though he has no hacks.
¨I know little information, I just don't know how to explain it.. xddd

Verbose Message
None

Cardinal Version: Latest

Spigot Version: 1.8.8 paper

> **Attached Video  (Required)**
https://youtu.be/9ooMFP3SmKw

**Comment by Clientastisch** [comment]
This false postive will be fixed in version 0.9995
