### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by PlesCZ** [Clientastisch/Cardinal-Anticheat#125]
What type of bug you want to report? Describe it here
I don't understand in Replay mode why NPCs levitate when he only had Scaffold :D 

When does the bug occurr?
In Replay

Cardinal Version: Latest

Spigot Version: 1.8.8 spigot

> **Attached Files  (Required)**
https://youtu.be/M6aQxHmk3xw

**Comment by Clientastisch** [comment]
this will be (most likely) be fixed in version 0.9995
