### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by Michal99998** [Clientastisch/Cardinal-Anticheat#127]
What type of bug you want to report? Describe it here
The plugin does not work

When does the bug occurr?
Typing /cac
It ignores hackers

Cardinal Version: 0.9995

Spigot Version: git-Paper-1490 (1.12.2)

> **Attached Files  (Required)**
![pic1](https://user-images.githubusercontent.com/59791284/89065432-f7c3ff00-d36b-11ea-9019-974e0c735f76.png)

**Comment by Clientastisch** [comment]
It seems that cac is disabled or not properly loaded, this sometimes happen with spigot. However this shoudn't be reproducible
