### ISSUE TITLE
False Positive | 

### ISSUE THREAD

**Issue by Martin1918** [Clientastisch/Cardinal-Anticheat#128]
How do you trigger the false positive? Describe it here
I'm just bug into a block

Verbose Message
https://gyazo.com/d8de71d9275bb8980ddcaa1716e909d8
https://gyazo.com/c325fbf5df1db8f94dc16cb3ac866a03

Proof:
https://gyazo.com/43175e58f9a8e7ce4f5a7f2cdce4a8ab

Cardinal Version: 
Latest
Spigot Version:
1.8.8

**Comment by Clientastisch** [comment]
Gonna be honest, no clue how to reproduce that... However, in the next version Phase will no longer kick by default. It'll just prevent you from going into blocks.
