### ISSUE TITLE
Bug Report | KillAura NPC

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#129]
What type of bug you want to report? Describe it here
I think that when attacking an NPC while hacking with KillAura, the AntiCheat moves the NPC behind the player instead of creating it's own one instead

When does the bug occurr?
When attacking an NPC while hacking with KillAura

Cardinal Version: 0.9997

Spigot Version: Paper 1.8.8

> **Attached Files  (Required)** https://www.youtube.com/watch?v=On0qoKt-IAo

**Comment by Clientastisch** [comment]
What's not big, but a check to make sure the player is truly hacking, the target itself won't be affected because the server handles the location of entities for each player on its own

**Comment by Jakaboii** [comment]
What do you mean? The NPC isn't supposed to move by itself

**Comment by Clientastisch** [comment]
It's not moving at all, just client-sided and it will be teleported back

**Comment by Jakaboii** [comment]
Oh? Because when using other anticheats/no anticheats at all, it doesn't move
And when enabling tracking (KillAura will follow the target) then it follows it to behind me and back

**Comment by Clientastisch** [comment]
It's just a concept I invented, of course no other anticheat is doing that. That's the point of being unique and no bypasses are existing because of that. 

You also just could disable `AimAssist Type D`

**Comment by Jakaboii** [comment]
Oh, OK
"That's the point of being unique and no bypasses are existing because of that." when I was hacking though, I wasn't being flagged for anything

**Comment by Clientastisch** [comment]
because you killaura wasn't snapping, or not fast enogh

**Comment by Jakaboii** [comment]
I tried while snapping too, let me send another video
Give me a few minutes
