### ISSUE TITLE
False Positive | 

### ISSUE THREAD

**Issue by PlesCZ** [Clientastisch/Cardinal-Anticheat#130]
How do you trigger the false positive? Describe it here
During the sprint, I will open the menu (GUI) and I'll get ban :D 

Verbose Message
I dont know

Cardinal Version: 0.9998

Spigot Version: Paper spigot 1.8.8

> **Attached Video  (Required)**
https://youtu.be/8xLQ9DQ7t6o

**Comment by Clientastisch** [comment]
Restart your server, should be fixed

**Comment by ERIS-VN** [comment]
I have the same problem, I restarted the server many times but it still ban me when I open GUI
I had to turn off the invmove check to solve the problem
