### ISSUE TITLE
Feature Request | Replay 

### ISSUE THREAD

**Issue by trashcanolives** [Clientastisch/Cardinal-Anticheat#134]
Please make it so replays can be saved right as someone is banned.
For some reason, you have to wait for the server to restart, to be able to load a replay.

**Comment by Clientastisch** [comment]
This is meant to save storage as the replays aren't that small (~ 5MB)
Imagine a case where several players get banned in a single BedWars round, that would waste unnecessary storage

**Comment by trashcanolives** [comment]
I don't understand?
Why do you have to wait till restart to be able to view replays?

**Comment by Clientastisch** [comment]
Because the replays are actually build while stopping the server

**Comment by trashcanolives** [comment]
Could you make it so replays are built right as someone gets banned?

**Comment by Clientastisch** [comment]
As I said this would waste storage the replay would be build anyway at the end. 
What happens if many players get banned dugin the session ?
