### ISSUE TITLE
Feature Request | API

### ISSUE THREAD

**Issue by trashcanolives** [Clientastisch/Cardinal-Anticheat#135]
Can you consider making an API, through which we can get important information about a ban, 
control checks, etc.

I want to code a /history <player> menu but I don't know how to fetch a player's ban status, replay id, etc.

**Comment by trashcanolives** [comment]
This could allow for us to code a Discord bot for example, that tags staff if a player is suspected.

**Comment by Clientastisch** [comment]
Read the documentation ^^ This feature already exists
https://github.com/Clientastisch/Cardinal-Anticheat/blob/master/ADDON.md

**Comment by trashcanolives** [comment]
sounds good thanks!
