### ISSUE TITLE
Feature Request | 

### ISSUE THREAD

**Issue by EvaneosKOWAR** [Clientastisch/Cardinal-Anticheat#137]
Why the fuck did you copy my anti-cheat name

**Comment by Thookuwu** [comment]
:v chupalo weon el hizo el anticheat mucho antes que vos

**Comment by Clientastisch** [comment]
Perhabs you just stole my anticheat name
![explorer_RLBs68xJYL](https://user-images.githubusercontent.com/51415855/95379040-1d7a0100-08e5-11eb-9401-f0fb8bc347de.png)
Change it !
