### ISSUE TITLE
False Positive | HitBox Type A

### ISSUE THREAD

**Issue by Thookuwu** [Clientastisch/Cardinal-Anticheat#138]
How do you trigger the false positive? Describe it here
When hit a player or NPC

Verbose Message
CAC: JavaBits tried HitBox Type A: 2.147483647E9
Kick=Yes Count=1 Ping=1

Cardinal Version: 1.0003

Spigot Version: 1.12.2

> **Attached Video  (Required)**
   https://youtu.be/d2-IeeqWXjY

**Comment by Clientastisch** [comment]
Should be fixed in the next version (1.0004)
