### ISSUE TITLE
False Positive | BlockHit Type B

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#141]
How do you trigger the false positive? Describe it here
I was block hitting an NPC and then got kicked for Hacking

Verbose Message
In video

Cardinal Version: 1.0005

Spigot Version: PaperSpigot 1.8.8

> **Attached Video  (Required)**
https://www.youtube.com/watch?v=2AlQKCHiJ0s

**Comment by Clientastisch** [comment]
Should be solved in the upcoming version (1.0006)
