### ISSUE TITLE
Bug Report | MariaDialect replay error

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#144]
What type of bug you want to report? Describe it here
When being banned, I have CAC configured to save replays to `//plugins//CAC//replays` in the Config.yml file
But when using MariaDialect, I got this error in the console: https://hatebin.com/mgscdgbqkr

I should also say that when being banned, I can rejoin (probably because of the error)

When does the bug occurr?
When being punished

Cardinal Version: 1.0005

Spigot Version: PaperSpigot 1.8.8

> **Attached Files  (Required)**
https://hatebin.com/mgscdgbqkr

**Comment by Clientastisch** [comment]
Download the newest version of the dialect and make sure to delete the tables
