### ISSUE TITLE
Bug Report | Replay error when restarting

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#145]
What type of bug you want to report? Describe it here
Whenever I restart the server to save a replay, CAC throws this error into the console: https://hatebin.com/ikcbccuqrp

When does the bug occurr?
When restarting the server

Cardinal Version: 1.0005

Spigot Version: PaperSpigot 1.8.8

> **Attached Files  (Required)**
https://hatebin.com/ikcbccuqrp

**Comment by Clientastisch** [comment]
you need to use `//` in your Config.yml

**Comment by Jakaboii** [comment]
> 
> 
> you need to use `//` in your Config.yml

I am using `//` in my Config.yml

**Comment by Jakaboii** [comment]
I have it set to `path: //plugins//CAC//replays`

**Comment by Clientastisch** [comment]
Try `plugins//CAC//replays` and make sure that there is a replay folder

**Comment by Jakaboii** [comment]
Ah, removing the `//` at the start fixed it, thanks
