### ISSUE TITLE
Bug Report | Replay error

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#146]
What type of bug you want to report? Describe it here
When trying to load a replay, CAC throws this error to the console: https://hatebin.com/pfujqotvno

When does the bug occurr?
When loading a replay

Cardinal Version: 1.0005

Spigot Version: PaperSpigot 1.8.8

> **Attached Files  (Required)**
https://hatebin.com/pfujqotvno

**Comment by Clientastisch** [comment]
That's because of WorldGuard

**Comment by Jakaboii** [comment]
Is there any way you can add WorldGuard compatibility?

**Comment by Clientastisch** [comment]
I would recommend to have a custom replay server

**Comment by Jakaboii** [comment]
A custom replay server?

**Comment by Clientastisch** [comment]
Yes, a server only for replays

**Comment by Jakaboii** [comment]
How would I do that?

**Comment by Clientastisch** [comment]
You create a new server which has CAC and maybe some plugins you want and use it to load the replays while the players play on other servers. 

I recommend to save all replays in the same folder for that

**Comment by Jakaboii** [comment]
> 
> 
> You create a new server which has CAC and maybe some plugins you want and use it to load the replays while the players play on other servers.
> 
> I recommend to save all replays in the same folder for that

But to do that I'd have to download every replay and transfer it to the other server.. and with my slow internet that'd take too long for me to look at a single replay, surely there's just a way you can add compatibility?

**Comment by Clientastisch** [comment]
I try to stay away from adding compatibility and I don't even know why there're exception in WorldGurad events.
I don't even mean to download the replays, but to create a new server on your vserver and start it there

**Comment by Jakaboii** [comment]
I still don't understand how I'd do that.. I run Pterodactyl Panel

**Comment by Clientastisch** [comment]
That might me an issue...
In that cause, wouldn't be a replay unnecessary?
Let's just write on discord ^^

**Comment by Jakaboii** [comment]
Ok
