### ISSUE TITLE
Bug Report | CAC duplicating NPC's

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#148]
What type of bug you want to report? Describe it here
CAC duplicates NPC's after you hit them, this is probably because of another check like AimAssist D, but I don't know what one to disable.

When does the bug occurr?
When hitting an NPC

Cardinal Version: 1.0005

Spigot Version: PaperSpigot 1.8.8

> **Attached Files  (Required)**
![image](https://user-images.githubusercontent.com/50416254/103900577-dc65d880-50ef-11eb-8a74-b41597c1a0d7.png)

**Comment by Clientastisch** [comment]
The only check that would come to my mind is `AntiBot Type A`

**Comment by Clientastisch** [comment]
Should be fixed in the upcoming  version (1.0006)
