### ISSUE TITLE
False Positive | Fly Type a c And Nofall

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#15]
How do you trigger the false positive? Describe it here
if you go down blocks with a slab up and tower them sideways like in the video you will false Fly type a and c walking down them and nofall you will false

Verbose Message
In The Video

Cardinal Version: 0.9958
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/rgqbg

**Comment by Clientastisch** [comment]
Thank you for your report, you issue is fixed in version 0.9959 and will be available soon!
