### ISSUE TITLE
This is a Trojan <-- DO NOT RUN

### ISSUE THREAD

**Issue by SoupOrSoda** [Clientastisch/Cardinal-Anticheat#152]
Do not run it, if you have ran it please delete your server jar and replace it with a new one. There is malicious code in this.

**Comment by Jakaboii** [comment]
CAC is very much not a trojan.. if you think so would you like to provide proof of the malicious code?

**Comment by pleumz** [comment]
Proof?

**Comment by SoupOrSoda** [comment]
Nvm it might be legit, just hiding the source

**Comment by SoupOrSoda** [comment]
Well essentially it was a few kilobytes, and it didn't look very legit

**Comment by ScaredDev** [comment]
You just don't have a plan about the CAC code little donkey.

**Comment by SoupOrSoda** [comment]
> You just don't have a plan about the CAC code little donkey.

lmao it was just 4kb, sorry for the inconveniences.

**Comment by Jakaboii** [comment]
Yes.. it's legit.. It's only a couple of kilobytes because CAC uses a loader

**Comment by SoupOrSoda** [comment]
> Yes.. it's legit.. It's only a couple of kilobytes because CAC uses a loader

Yeah I just realised, sorry about this
