### ISSUE TITLE
False Positive | Phase And yMotion

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#17]
How do you trigger the false positive? Describe it here
if you use a sticky piston or piston with a block on it going upwards and you get on it flick the lever it will push you up and you will false phase and ymotion

Verbose Message
In The Video

Cardinal Version: 0.9958
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/g8kyj

**Comment by Clientastisch** [comment]
Thank you for your report, your issue is fixed in version 0.9949 which will be available soon
