### ISSUE TITLE
Feature Request | Help Command

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#18]
What features would you like added? Describe them here
when you do /cac or /cac help instead of it slowing going through the commands in  the middle of your screen make it just show all the commands in chat for you so you dont need a big thing slowly going through all the commands in your face in the middle of the screen

**Comment by Clientastisch** [comment]
Thank you for you suggestion, I have considered your suggestion in version 0.9963
