### ISSUE TITLE
False Positive | Fly Type H

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#19]
How do you trigger the false positive? Describe it here
when you go down stairs then up a stairs block one block away at the very bottom

Verbose Message
In The Video

Cardinal Version: 0.9958
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/y8y4s

**Comment by Clientastisch** [comment]
Thank you for your report, you issue is fixed in version 0.9959 and will be available soon!
