### ISSUE TITLE
False Positive | Fly Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#21]
How do you trigger the false positive? Describe it here
if you have the gadgetsmenu plugin and use the trampoline gadget and just stay on the trampoline after the first 2 jumps in the air you will start falsing fly type a

Verbose Message
In The Video

Cardinal Version: 0.9958
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/y25j3

**Comment by Clientastisch** [comment]
Thank your for your report, your issue will be mostly solved in version 0.9980
