### ISSUE TITLE
False Positive | Jesus Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#23]
How do you trigger the false positive? Describe it here
if you sprint on top of water with carpets on it you will false jesus type a

Verbose Message
in the video

Cardinal Version: 0.9958
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/1jify

**Comment by Clientastisch** [comment]
Thank you for your report, you issue is fixed in version 0.9959 and will be available soon!
