### ISSUE TITLE
False Positive | Speed Type C

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#24]
How do you trigger the false positive? Describe it here
if you have wither skeleton skulls 2 blocks above you and you sprint and jump you will false speed type c

Verbose Message
in the video

Cardinal Version: 0.9958
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/o64so

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9959 which will be available soon
