### ISSUE TITLE
False Positive | Jesus Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#28]
How do you trigger the false positive? Describe it here
if you have water going down blocks like in the video then holding spacebar and sprinting down you will false jesus type a

Verbose Message
In The Video

Cardinal Version: 0.9958
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/y5pbq

**Comment by Clientastisch** [comment]
Thank you for your report, you issue is fixed in version 0.9959 and will be available soon!
