### ISSUE TITLE
Speed Type J E And Strafe Type A False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#3]
if you have the essentials plugin which almost every server has https://dev.bukkit.org/projects/essentials if you do /speed 2 it will false speed type j and if you do /speed 4 it will false speed type j and e oh and if you move to the sides you will false strafe type a with that heres a video of it https://streamable.com/ugoni

**Comment by Clientastisch** [comment]
Thank you for your report, you issue is fixed in version 0.9956 and will be available soon!
