### ISSUE TITLE
False Positive | Speed Type E

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#30]
How do you trigger the false positive? Describe it here
if you have ice under you and trapdoors above your head a long way down like a tunnel then sprint and spam the crap out of your spacebar you will false speed type e

Verbose Message
in the video

Cardinal Version: 0.9958
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/0ahgi

**Comment by Clientastisch** [comment]
Thank you for your report, you issue is fixed in version 0.9959 and will be available soon!
