### ISSUE TITLE
question

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#31]
question why when i have the anticheat installed on my server the command /aac pops up?? and ncp is this a aac skid or ncp skid or something? lol

**Comment by Clientastisch** [comment]
No, / aac and / ncp are the most executed. No One would execute /cac and I want to be a bit more known

**Comment by coolpvpv1** [comment]
> No, / aac and / ncp are the most executed. No One would execute /cac and I want to be a bit more known

um ok then
