### ISSUE TITLE
Bug Report | Manage

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#34]
What type of bug you want to report? Describe it here
when you do /cac manage someone then try to ban them it says couldn't connect properly to sql

When the bug occurrs?
when you do /cac manage someone then try to ban them it says couldn't connect properly to sql

Cardinal Version: 0.9958
Spigot Version: 1.8.8

Attached Files
none?

**Comment by Clientastisch** [comment]
Banning a player requires an active connection to a database. Otherwise, how should the plugin save the ban ?
