### ISSUE TITLE
Bug Report | Noswing Type A With PvP Bot And Ymotion

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#37]
What type of bug you want to report? Describe it here
if you have strikepractice then do a pvp bot and once it tries to hit you it spams noswing type a falses and strikepractices custom knockback falses ymotion

When the bug occurrs?
when you fight the pvp bot on strikepractice and have custom kb on in strikepractice config

Cardinal Version: 0.9961
Spigot Version: 1.8.8

Attached Files
https://streamable.com/rec03

**Comment by Clientastisch** [comment]
Lol...
I'll look how I can fix this. I guess that the NPC is shown as a Bukkit online player.
That would make things harder

**Comment by coolpvpv1** [comment]
> Lol...
> I'll look how I can fix this. I guess that the NPC is shown as a Bukkit online player.
> That would make things harder

it doesn't show it as a online player in tab or /list

**Comment by Clientastisch** [comment]
Could you do /cac gui and see if you can whitelist the bot ?

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9973
