### ISSUE TITLE
False Positive | Fly Type A C And D

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#38]
How do you trigger the false positive? Describe it here
if you have a cobweb like 3 blocks in the air and go in it at the end where you start to almost get out of the cobweb you will false Fly Type D And if you go on the side you will false A And C

Verbose Message
In The Video

Cardinal Version: 0.9961
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/wq0jl

**Comment by Clientastisch** [comment]
Thank you for you report, this issue will be fixed in version 0.9963
