### ISSUE TITLE
False Positive | Fly Type I And A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#39]
How do you trigger the false positive? Describe it here
if you go 255 blocks up then fall on slime while moving sometimes you'll false Fly Type A And I

Verbose Message
In The Video

Cardinal Version: 0.9961
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/rik2c

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9963
