### ISSUE TITLE
False Positive | NoWeb

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#40]
How do you trigger the false positive? Describe it here
if you go on the side of a cobweb that has another cobweb below it in the air and slowly go down on the edge of it you will false NoWeb

Verbose Message
In The Video

Cardinal Version: 0.9961
Spigot Version: 1.8.8

Attached Video  (Required)
https://streamable.com/1jaf9

**Comment by Clientastisch** [comment]
Thank you for your report, you issue will be fixed in version 0.9973
