### ISSUE TITLE
Feature Request | 

### ISSUE THREAD

**Issue by XITheGrayWolfIX** [Clientastisch/Cardinal-Anticheat#43]
**What features would you like added? Describe them here**

We need a Killaura Bot, One like Gwen that learns
Also, could you remove the CAC title animations and just make it a message, it gets really ignoring
![image](https://user-images.githubusercontent.com/44043990/69470942-13e4ba80-0d60-11ea-9dce-5fad0102a299.png)

**Comment by lukasl-dev** [comment]
You can execute /cac abort for the Title-Cancelling. :)

**Comment by Clientastisch** [comment]
If you just  wanna see a list of all commands do /CAC help.
And please describe what you mean by a Killaura Bot that "learns" ?
