### ISSUE TITLE
Bug Report | alert and flag command

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#44]
What type of bug you want to report? Describe it here
you use to be able to do /cac flags and /cac alerts but now its only /cac flag and /cac alert

When the bug occurrs?
you cant do /cac flags or /cac alerts anymore only /cac flag or /cac alert

Cardinal Version: 0.9972
Spigot Version: 1.8.8

Attached Files
none

**Comment by Clientastisch** [comment]
That's something you have to get used to
