### ISSUE TITLE
Bug Report | direct connect

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#45]
What type of bug you want to report? Describe it here
when you get kicked by cac for hacking then try to rejoin on a localhost server it says unable to create connection from direct connect please add the server to your serverlist

When the bug occurrs?
when you get kicked by cac for hacking then try to rejoin on a localhost server it says unable to create connection from direct connect please add the server to your serverlist

Cardinal Version: 0.9972
Spigot Version: 1.8.8

Attached Files
none

**Comment by coolpvpv1** [comment]
also mistype in the kick message at serverlist xd

**Comment by Clientastisch** [comment]
Just disable AntiBotting
