### ISSUE TITLE
False Positive | Velocity Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#46]
How do you trigger the false positive? Describe it here
if you use this plugin https://www.spigotmc.org/resources/custom-jumppads-1-8-1-14.44876/ and do /jp create 25 25 or higher you will false Velocity Type A (first 25 is power and the second 25 number is for angle)

Verbose Message
In The Video

Cardinal Version: 0.9972
Spigot Version: 1.8.8

Attached Video  (Required)
obs aint working rn idk why so i cant do a video

**Comment by Clientastisch** [comment]
The problem is, that it sets every tick a new velocity. This triggers the false positive on CAC and NCP. NCP doen't flag the player because the plugin uses the NPC Api to whitelist the player. If you would be a server owner you can disable Velocity Type A or also code an addon with the CAC Api
