### ISSUE TITLE
Bug Report | console error when npc takes damage

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#47]
What type of bug you want to report? Describe it here
when a pvp bot or a npc takes damage it gives a big error in console https://paste.ubuntu.com/p/zHQXhvgGWB/ 

When the bug occurrs?
when a pvp bot or a npc takes damage it gives a big error in console https://paste.ubuntu.com/p/zHQXhvgGWB/

Cardinal Version: 0.9972
Spigot Version: 1.8.8

Attached Files
https://paste.ubuntu.com/p/zHQXhvgGWB/

**Comment by Clientastisch** [comment]
I cannot find the cause by this exception.

**Comment by Clientastisch** [comment]
What kind of flags do appear ?

**Comment by Clientastisch** [comment]
It seems like an external exception not caused by Cardinal Anticheat. So I am unable to fix this exception
