### ISSUE TITLE
when antiviruses hate you

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#48]
https://www.virustotal.com/gui/file/c20646215626508d11755725ec6ef5bcd9fd469dc12925c156aac2259e5f06bf/detection xD ik its not a virus but antiviruses murder this lol

**Comment by Clientastisch** [comment]
lul, at the very beginning just one antivirus cried... I've no idea how I can fix this. Probably it's because of the obfuscation... idk

**Comment by coolpvpv1** [comment]
> lul, at the very beginning just one antivirus cried... I've no idea how I can fix this. Probably it's because of the obfuscation... idk

heres the places if you want to report the false positives to the antivirus companys
Arcabit: virus@arcabit.com (cant find online site to report falses and attach password protected 7z file)
Comodo: https://www.comodo.com/home/internet-security/submit.php
FireEye: cant find link to report falses
GData: cant find link either
MAX: cant find link either
Bitdefender: http://www.bitdefender.com/site/Main/automaticSampleUploader/ (choose false positive in category)
Escan: http://support.mwti.net/support/index.php (i think you have to make a account for it idk)
Fortinet: submitvirus@fortinet.com (cant find online site to report falses)
Ikarus: probe@ikarus.at (cant find online site to report falses)
McAfee-GW-Edition: virus_research_gateway@avertlabs.com (theres a site for falses but if its gw edition it has to be through this email)
