### ISSUE TITLE
Bug Report | ServerCrasher

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#49]
What type of bug you want to report? Describe it here
LiquidBounce ServerCrasher Mode Cubecraft works and crashes the server and it doesn't without cardinal so idk if its something wrong with cardinal but with it on the server crashes and without it the server doesn't crash

When the bug occurrs?
When you use liquidbounce servercrasher mode cubecraft

Cardinal Version: 0.9973
Spigot Version: 1.8.8

Attached Files

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9975
