### ISSUE TITLE
Bug Report | weird kick when you teleport super far

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#50]
What type of bug you want to report? Describe it here
lets say your like at 0 150 0 in coords if you do like /tp (name) 200 150 200 it will kick you for this
[22:56:54 INFO]: Olaeak lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Asynchronous entity world add!
[22:56:54 INFO]: Olaeak left the game.

When the bug occurrs?
when you do /tp (name) 200 150 200 (or any coords atleast like 200 blocks away) it will kick you

Cardinal Version: 0.9973
Spigot Version: 1.8.8

Attached Files

**Comment by Clientastisch** [comment]
Does this only occurrs if you teleport the player with commands or also if you teleport the player by plugin ?

**Comment by coolpvpv1** [comment]
> Does this only occurrs if you teleport the player with commands or also if you teleport the player by plugin ?

both on strikepractice when it tps a player like 500 players away to go in a arena it also kicks the player for the same thing

**Comment by coolpvpv1** [comment]
> Does this only occurrs if you teleport the player with commands or also if you teleport the player by plugin ?

heres the places if you want to report the false positives to the antivirus companys
Arcabit: virus@arcabit.com (cant find online site to report falses and attach password protected 7z file)
Comodo: https://www.comodo.com/home/internet-security/submit.php
FireEye: cant find link to report falses
GData: cant find link either
MAX: cant find link either
Bitdefender: http://www.bitdefender.com/site/Main/automaticSampleUploader/ (choose false positive in category)
Escan: http://support.mwti.net/support/index.php (i think you have to make a account for it idk)
Fortinet: submitvirus@fortinet.com (cant find online site to report falses)
Ikarus: probe@ikarus.at (cant find online site to report falses)
McAfee-GW-Edition: virus_research_gateway@avertlabs.com (theres a site for falses but if its gw edition it has to be through this email)

**Comment by coolpvpv1** [comment]
> Does this only occurrs if you teleport the player with commands or also if you teleport the player by plugin ?

on comodo antivirus its says it detects something in the config.class idk why

**Comment by coolpvpv1** [comment]
> Does this only occurrs if you teleport the player with commands or also if you teleport the player by plugin ?

![Screenshot (4)](https://user-images.githubusercontent.com/54179810/69831834-20459900-11e0-11ea-871c-cbfa80f85734.png)

**Comment by Clientastisch** [comment]
First of all, you issue with the weird kick will be fixed in version 0.9974. However I'm damn confused why the hell it says that classes like my damn config are malware lol... That's obviously the obfuscators fault. But I don't think I'll report this, it's just to much work
