### ISSUE TITLE
False Positive | Speed Type I

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#51]
How do you trigger the false positive? Describe it here
if you have ice on the ground then trapdoors above your head so you can sprint and jump and go super fast on ice you will false speed type i but you need it to be like 20 blocks long or 30

Verbose Message
obs being stupid so i cant record

Cardinal Version: 0.9973
Spigot Version: 1.8.8

Attached Video  (Required)
obs being stupid so i cant record

**Comment by Clientastisch** [comment]
Thank you for your report, you issue will be fixed in version 0.9974
