### ISSUE TITLE
False Positive | Vclip Type A False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#52]
How do you trigger the false positive? Describe it here
if you have essentials and do /fly then fly up like 20 blocks when you fall like 10 blocks down and do /fly again to turn it off you for some reason you false Vclip Type A

Verbose Message
obs being retarded as usual so i cant record

Cardinal Version: 0.9974
Spigot Version: 1.8.8

Attached Video  (Required)
obs being retarded as usual so i cant record

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9975
