### ISSUE TITLE
False Positive | AntiCactus

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#53]
How do you trigger the false positive? Describe it here
if you place a carpet on top of a cactus then stand on it with the carpet on it you will false AntiCactus

Verbose Message
obs having a mental breakdown so no video

Cardinal Version: 0.9974
Spigot Version: 1.8.8

Attached Video  (Required)
obs having a mental breakdown so no video

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9975
