### ISSUE TITLE
False Positive | Vport Type A Nofall (sometimes) And Fly Type J

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#54]
How do you trigger the false positive? Describe it here
if you have redstone repeators constantly repeating redstone to a piston and just then stand on the piston pushing you up constantly and just sit there for like 30 seconds then go back you will see it falses Vport Type A Nofall (sometimes) And Fly Type J screenshot https://i.imgur.com/tbgNWHV.png

Verbose Message
obs having mental breakdown so i cant record

Cardinal Version: 0.9974
Spigot Version: 1.8.8

Attached Video  (Required)
obs having mental breakdown so i cant record

**Comment by Jakaboii** [comment]
aaand was this fixed?

**Comment by Clientastisch** [comment]
Mostly, but it's hard to fix because pistons are ugly
In fact, most Anticheats have issues with pistons
