### ISSUE TITLE
False Positive | Speed Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#55]
How do you trigger the false positive? Describe it here
if you have a huge line of pistons then sprint down it you will false Speed Type A https://i.imgur.com/f95y2eM.jpg xD

Verbose Message
obs having mental breakdown so i cant record

Cardinal Version: 0.9974
Spigot Version: 1.8.8

Attached Video  (Required)
obs having mental breakdown so i cant record

**Comment by Clientastisch** [comment]
I've two very simple ways to fix this and other issues

(1) If player get distance to next piston < 2.5 -> return
(2) piston setType air

Which is better ? xd

**Comment by coolpvpv1** [comment]
> I've two very simple ways to fix this and other issues
> 
> (1) If player get distance to next piston < 2.5 -> return
> (2) piston setType air
> 
> Which is better ? xd

what

**Comment by Clientastisch** [comment]
Just kidding, I'll try to fix it

**Comment by coolpvpv1** [comment]
> Just kidding, I'll try to fix it

guess what anticheats on the anticheat list wikis now :) https://www.spigotmc.org/wiki/anti-cheat-list-bukkit-and-spigot-1-8-x/

**Comment by Clientastisch** [comment]
Lol, did you added Cardinal on the list ? xd

**Comment by coolpvpv1** [comment]
> Lol, did you added Cardinal on the list ? xd

xd yes

**Comment by Clientastisch** [comment]
Thank's :)

**Comment by Jakaboii** [comment]
was this fixed?
