### ISSUE TITLE
False Positive | AirWalk Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#56]
How do you trigger the false positive? Describe it here
if you go up like 10 blocks place a cobweb then go in it and if you move around in the cobweb near the bottom where your almost going to fall off you will false AirWalk Type A Fly a ton

Verbose Message
obs having mental breakdown so i cant record

Cardinal Version: 0.9974
Spigot Version: 1.8.8

Attached Video  (Required)
obs having mental breakdown so i cant record

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be solved in version 0.9979
