### ISSUE TITLE
Bug Report | Version Null

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#57]
What type of bug you want to report? Describe it here
if you use badlion client then set off a check and when you hover over it to see the version it says null https://i.badlion.net/rm8kowWZTfPhfJFfqNmf6M.png

When the bug occurrs?
if you use badlion client then set off a check and when you hover over it to see the version it says null https://i.badlion.net/rm8kowWZTfPhfJFfqNmf6M.png

Cardinal Version: 0.9974
Spigot Version: 1.8.8

Attached Files
https://i.badlion.net/rm8kowWZTfPhfJFfqNmf6M.png

**Comment by Clientastisch** [comment]
That's not a bug. I cannot say what you are using when the anticheat doesn't get the needed payload packet. This packet will only be sent on join, just rejoin and there will be vanilla or else

**Comment by Clientastisch** [comment]
And the bot never sends this packet, so null is quiet right ^^
