### ISSUE TITLE
Bug Report | Console Error When Npc Damages You

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#58]
What type of bug you want to report? Describe it here
That old console error that said ncp damage error and other crap i found out it only when the npc attacks you the error occurs not when you attack the npc heres the error https://paste.ubuntu.com/p/yqyGx6RbFS/ 

When the bug occurrs?
when a npc damages you using im strikepractice for the bots to attack you btw idk if you can make bots damage you on normal citizens if theres a way to do it i dont know how to so big oof

Cardinal Version: 0.9974
Spigot Version: 1.8.8

Attached Files
no u

**Comment by Clientastisch** [comment]
Hopefully I fixed this issue in version 0.9975 xd
