### ISSUE TITLE
False Positive | WallAttack Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#59]
How do you trigger the false positive? Describe it here
if you have trapdoors above your head and try to hit a entity with the trapdoors right above your head you will false https://i.badlion.net/24EBV6vmPofRGNZXEbzAif.png

Verbose Message
https://i.badlion.net/24EBV6vmPofRGNZXEbzAif.png

Cardinal Version: 0.9974
Spigot Version: 1.8.8

Attached Video  (Required)
obs gay so i cant

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9975
