### ISSUE TITLE
yMotion Fly Type A C I and Airwalk type A False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#6]
if you have essentials plugin https://dev.bukkit.org/projects/essentials and do /fly to fly up then type it in chat again and you will fall down and sometimes you will either false ymotion fly type a c i or airwalk type a but heres a video of me doing it https://streamable.com/4wv94

**Comment by Clientastisch** [comment]
Thank you for your report, you issue is fixed in version 0.9956 which will be available soon!
