### ISSUE TITLE
Bug Report | Bots False Hitbox Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#60]
What type of bug you want to report? Describe it here*
strikepractice bots false Hitbox Type A sense i saw the noswing type a bug was fixed i though you could fix this one to so im just reporting it

When the bug occurrs?
when you fight a strikepractice bot and move around it a little bit

Cardinal Version: 0.9974
Spigot Version: 1.8.8

Attached Files
no u

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9975
