### ISSUE TITLE
Bug Report | Speed Type G

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#61]
What type of bug you want to report? Describe it here
in /cac gui if you go to punishments and remove the setbacks for Speed Type G it will still set you back even if you turned off setbacks

When the bug occurrs?
in /cac gui if you go to punishments and remove the setbacks for Speed Type G it will still set you back even if you turned off setbacks

Cardinal Version: 0.9974
Spigot Version: 1.8.8 

Attached Files
cac

**Comment by Clientastisch** [comment]
Thank you for your report, I forgot to change the method xd. Your issue will be fixed in version 0.9975
