### ISSUE TITLE
Bug Report | Kicked on login

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#64]
**What type of bug you want to report? Describe it here**

The Anticheat just kicks me for no reason sometimes when I login, this never happened before
When it kicks me, the console sends this:

`
> [INFO]: UUID of player Jakaboii is 806f3a1c-6ae2-4dc9-b3c2-53bb32c673f2
> [NFO]: Jakaboii logged in with entity id 99 at ([world]96.49263298478306, 81.36933695946747, 85.50446359903526)
> [INFO]: Jakaboii lost connection: ?c?lCAC
?c?lKicked?r
?cReason: ?6?lAntiCheat detection?r
> [WARN]: handleDisconnection() called twice
> [WARN]: handleDisconnection() called twice
> [WARN]: handleDisconnection() called twice
> [WARN]: handleDisconnection() called twice
> [WARN]: handleDisconnection() called twice
`

**When the bug occurrs?**
When I try to login to the server

**Cardinal Version:** 0.9974
**Spigot Version:** Paper 1.8.8 (Travertine for the Proxy server)

**Attached Files**
none

**Comment by Jakaboii** [comment]
Here's a video too: the video is inside the .zip (It has to be a .zip because github doesn't support .mp4)



[Kicked.zip](https://github.com/Clientastisch/Cardinal-Anticheat/files/3952332/Kicked.zip)

**Comment by Clientastisch** [comment]
I'll take a look at it, but it looks like the NetFrequence check. I'll take care of this

**Comment by Jakaboii** [comment]
OK, thanks a lot
I'll disable the check and see what happens

**Comment by Jakaboii** [comment]
Yup, it works fine now

**Comment by Clientastisch** [comment]
Okay, I've fixed that in version 0.9975 which will be available soon
