### ISSUE TITLE
Feature Request | 1.13.2 Support (and a little more requests)

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#65]
**What features would you like added? Describe them here**
I know that 1.12.2 support just released (good job on that btw) but what would make this (literally) the best free anticheat, is 1.13.2 support

A discord server would also be pretty nice

And maybe instead of using the built-in BanManager, make it so you can set custom kick, mute, ban commands ect

**Comment by Jakaboii** [comment]
Also, to be able to change the prefix would be nice

**Comment by Clientastisch** [comment]
The prefix is only visable for stuffs, so I see no need in changing the prefix. Futhermore I own a discord for Cardinal: https://discord.gg/KMZQaU7

**Comment by Clientastisch** [comment]
The issue I'm currently facing, is that you have to select a api-version in you plugin.yml to get newer materials, like scaffolding or honey_block. But if I do so (api-version: 1.15) all servers below 1.15 wouldn't load this plugin anymore. I have the possibilaty to use reflections, but this needs damn performance

**Comment by Jakaboii** [comment]
If you could even make it up to 1.13.2 that'd be enough I'd say, not much servers are running 1.15 at the moment

**Comment by Jakaboii** [comment]
It'd also be nice to know the file changes on updates, so we don't have to keep deleting then reconfiguring the files each update

**Comment by Clientastisch** [comment]
You don't have to, I tell you if a configuration of a check has changed and the change very rarely

**Comment by Clientastisch** [comment]
I've changed my mind. I will add 1.13 support, but I don't think that there will be 1.14 and higher. But I also said there wouldn't be higher 1.8 so....
