### ISSUE TITLE
False Positive | Speed Type J And Fly Type D

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#66]
How do you trigger the false positive? Describe it here
if you go on 1.12.2 get a elytra then just spam jump at the ground running you will start falsing speed type j and fly type d sometimes

Verbose Message
obs stupid

Cardinal Version: 0.9975
Spigot Version: 1.12.2

Attached Video  (Required)
obs stupid

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9977
