### ISSUE TITLE
Bug Report | Console error fixed but still one check giving the error

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#67]
What type of bug you want to report? Describe it here
the wallattack type a error was fixed but hitbox b still gives this error in console xd https://paste.ubuntu.com/p/8y5WFRGSjg/

When the bug occurrs?
a ncp damaging you https://paste.ubuntu.com/p/8y5WFRGSjg/

Cardinal Version: 0.9975
Spigot Version: 1.8.8

Attached Files
no uuuuuuuuuuu

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9976

**Comment by coolpvpv1** [comment]
> Thank you for your report, your issue will be fixed in version 0.9976

the console error is no longer a thing now thats great xd
