### ISSUE TITLE
Bug Report | AutoArmor Type A (1.12.2)

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#68]
What type of bug you want to report? Describe it here
when you open your inventory on spigot 1.12.2 the helmet goes in your off hand and is just stuck in your off hand 

When the bug occurrs?
when you open your inventory on spigot 1.12.2

Cardinal Version: 0.9976
Spigot Version: 1.12.2

Attached Files
no uuuuuuuuuuuuuu

**Comment by Clientastisch** [comment]
This issue will probably never occurr, I've removed AutoArmor in version 0.7766
