### ISSUE TITLE
Bug Report | cac gui + 1.12.2 = cancer

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#69]
What type of bug you want to report? Describe it here
do /cac gui exit the gui open your inventory and you get free cancer

When the bug occurrs?
do /cac gui exit the gui open your inventory and you get free cancer

Cardinal Version: 0.9976
Spigot Version: 1.12.2

Attached Files
cancer

**Comment by Clientastisch** [comment]
I've noticed that either, this is because of AutoArmor Type A. This issue will be fixed in version 0.9977
