### ISSUE TITLE
NoSlowDown Type A False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#7]
if you run looking slightly down at the ground clicking for some reason it will false noslowdown idk why xd heres a video of it https://streamable.com/91p6l

**Comment by Clientastisch** [comment]
I tried to reproduce this one, but somehow I'm to stupid to do that xd Are you just clicking on the ground and sprinting forward ?

**Comment by Clientastisch** [comment]
Thank you for your report, you issue is fixed in version 0.9956 which will be available soon!
