### ISSUE TITLE
Bug Report | console errors on 1.12.2

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#70]
What type of bug you want to report? Describe it here
console error on 1.12.2 https://paste.ubuntu.com/p/njPNbN5wRB/

When the bug occurrs?
when i was just pvping the bot and crap idk https://paste.ubuntu.com/p/njPNbN5wRB/ 

Cardinal Version: v0.9976
Spigot Version: 1.12.2

Attached Files
cancer

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9977
