### ISSUE TITLE
Bug Report | cac command on 1.12.2

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#71]
What type of bug you want to report? Describe it here
you know in 1.8 it shows you the commands in front of your screen it doesn't on 1.12.2

When the bug occurrs?
when you do /cac and it doesn't show the commands in the middle of the screen

Cardinal Version: 0.9976
Spigot Version: 1.12.2

Attached Files
cancer

**Comment by Clientastisch** [comment]
I know, I've disabled it until I'm able to send it for every version

**Comment by coolpvpv1** [comment]
> I know, I've disabled it until I'm able to send it for every version

ok
