### ISSUE TITLE
False Positive | Phase on 1.12.2

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#72]
How do you trigger the false positive? Describe it here
if you get a shovel then left click the ground to make a grass path walk on it you will false Phase

Verbose Message
no

Cardinal Version: 0.9976
Spigot Version: 1.12.2

Attached Video  (Required)
obs is retarded

**Comment by coolpvpv1** [comment]
@Clientastisch also soil falses phase on 1.12.2

**Comment by Clientastisch** [comment]
What's the name of the block ?

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be fixed in version 0.9977
