### ISSUE TITLE
Bug Report | weird kick on 1.12.2

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#73]
What type of bug you want to report? Describe it here
i was just using enderpearls mining blocks and crap and got kicked for this https://paste.ubuntu.com/p/WBxVRb69nW/

When the bug occurrs?
idk i was just using enderpearls mining blocks and crap and got kicked for this https://paste.ubuntu.com/p/WBxVRb69nW/

Cardinal Version:
Spigot Version: 1.12.2

Attached Files
cancer

**Comment by Clientastisch** [comment]
This isn't just on version 1.12, but I guess it's fixed in version 0.7766
