### ISSUE TITLE
Feature Request | Some commands in console

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#76]
**What features would you like added? Describe them here**
It would be very useful if the console could use some important commands like `cac unban`, `cac ban` ect ect
Or make it so instead of BanManager we can set our own ban commands that a Punish plugin has (eg: AdvancedBan, Litebans ect)

**Comment by Clientastisch** [comment]
I will add them in version 0.9978. I had to fix some important multiversion issues first

**Comment by Jakaboii** [comment]
OK, ty
