### ISSUE TITLE
False Positive | WallAttack Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#77]
How do you trigger the false positive? Describe it here
if you have cobblestone walls go in the corner of them then try to hit something you will false WallAttack Type A https://i.badlion.net/trEzagy3Dj5FU3x2RUTyAj.png

Verbose Message
no but heres the false https://i.badlion.net/trEzagy3Dj5FU3x2RUTyAj.png

Cardinal Version: 0.9977
Spigot Version: 1.8.8

Attached Video  (Required)
obs stupid

**Comment by Clientastisch** [comment]
Thank you for you report, your issue will be solved in version 0.9978
