### ISSUE TITLE
Bug Report | 1.13.2 support = cancer console errors

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#78]
What type of bug you want to report? Describe it here
when i just joined on 1.13.2 it gave me all these errors in console
https://paste.ubuntu.com/p/vtqCSFXTWD/ and the anticheat doesn't work sense it keeps rebooting

When the bug occurrs?
when i just joined on 1.13.2 it gave me all these errors in console
https://paste.ubuntu.com/p/vtqCSFXTWD/ and the anticheat doesn't work sense it keeps rebooting

Cardinal Version: 0.9977
Spigot Version: 1.13.2

Attached Files
cancer

**Comment by Clientastisch** [comment]
Just on your first join ?

**Comment by Clientastisch** [comment]
Perhabs you are using an outdated or modified spigot version. Please use this one: 
https://workupload.com/file/fAdsq2hU

It has been made with the official BuildTools.jar a few days ago
