### ISSUE TITLE
False Positive | Speed Type I And G (1.13)

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#79]
How do you trigger the false positive? Describe it here
if you go to the build height limit jump off with a elytra on then when theres ground at the bottom you look up to glide super fastly and then you spam Speed Type I And G alerts btw make the limit on 1.13 2.5 for speed type i sense speed type i detects unlimitedelytraspeed hacks

Verbose Message
no

Cardinal Version: 0.9977
Spigot Version: 1.13

Attached Video  (Required)
obs super gay

**Comment by Clientastisch** [comment]
Thank you, your issue will be solved in version 0.9979
