### ISSUE TITLE
suggestion for formats

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#8]
you should have formats when you click the issues button you should choose from request, bug, bypass, false positive
heres the request format 
What features would you like added?
Describe it here:
heres the bug format

Console Error
Provide error messages here:

When the bug occurrs?
Describe when the bug occurrs:

Server Version:
Anticheat Version:
ProtocolLib Version:

heres the bypass format

Hack Client:
Hacking Type:
Link To Hacked Client:
Anticheat Version:
Server Version:

Videos
Please provide a bypass video link here:

heres the false positive format

How you trigger the false positive?
Describe how to trigger the false positive here:

Verbose Message:
Provide the verbose message here:

Videos:
If you recorded a video of false positive, put link here: 

Anticheat Version:
Server Version:
ProtocolLib Version:

**Comment by Clientastisch** [comment]
To be honest, I have no clue xd I've never used github before

**Comment by Clientastisch** [comment]
Oh I found it, thank you alot 😊😊👌
