### ISSUE TITLE
False Positive | Speed Type C (1.13)

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#80]
How do you trigger the false positive? Describe it here
if you find a dolphin when sprinting in water for the water swimming animation and get the dolphins grace effect and have depthstrider 1 2 or 3 on you will set off alot of speed type c alerts

Verbose Message
no

Cardinal Version: 0.9977
Spigot Version: 1.13

Attached Video  (Required)
obs stupid

**Comment by Clientastisch** [comment]
Thank you for your report, your issue will be solved in version 0.9979
