### ISSUE TITLE
False Positive | Phase

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#82]
How do you trigger the false positive? Describe it here
if you go on 1.13 get a hoe then left click the ground walk over the soiled ground and you will false phase soil

Verbose Message
obs stupid

Cardinal Version: 0.9978
Spigot Version: 1.13

Attached Video  (Required)
obs stupid

**Comment by Clientastisch** [comment]
If I leftcick the ground nothing happens. Also if I make dirt to farmland, it woun't false for Phase

**Comment by coolpvpv1** [comment]
> If I leftcick the ground nothing happens. Also if I make dirt to farmland, it woun't false for Phase

weird it falses for me

**Comment by Clientastisch** [comment]
You sure, you're playing the newest version ?

**Comment by coolpvpv1** [comment]
> You sure, you're playing the newest version ?

yes its on  1.13 and left click the ground next to water and try going on it

**Comment by Clientastisch** [comment]
Could you try once more to make a vid. I'm to stupid to understand what the hell you're talking about :p

**Comment by coolpvpv1** [comment]
> Could you try once more to make a vid. I'm to stupid to understand what the hell you're talking about :p

idk im just gonna close this issue
