### ISSUE TITLE
False Positive | uh idk billions of falses

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#83]
How do you trigger the false positive? Describe it here
if you go on 1.13 get a trident enchant it with riptide 3 and if the weather is raining and you launch straight up alot you will false vport type a fly type a fly type b and fly type g speed type g and speed type i and if you launch the trident at a mob when your right next to it you will false noswing type a

Verbose Message
obs stupid

Cardinal Version: 0.9978
Spigot Version: 1.13

Attached Video  (Required)
obs stupid

**Comment by coolpvpv1** [comment]
> How do you trigger the false positive? Describe it here
> if you go on 1.13 get a trident enchant it with riptide 3 and if the weather is raining and you launch straight up alot you will false vport type a fly type a fly type b and fly type g speed type g and speed type i and if you launch the trident at a mob when your right next to it you will false noswing type a
> 
> Verbose Message
> obs stupid
> 
> Cardinal Version: 0.9978
> Spigot Version: 1.13
> 
> Attached Video (Required)
> obs stupid

also falses if you have a elytra on and if your gliding with the elytra and using the trident to boost you will false speed type g and speed type i

**Comment by Jakaboii** [comment]
was this fixed?
