### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#84]
**What type of bug you want to report? Describe it here**
I was just running around with my friend at spawn talking, and next second it flagged them for fly and me for speed & vPort
A bit later it just banned  my friend without flagging them

**When the bug occurrs?**
When I'm just running around

**Cardinal Version:** 0.9978
**Spigot Version:** Paper 1.8

**Attached Files**
https://streamable.com/dhsqm

https://streamable.com/zljuq (this is a different issue, I uploaded the wrong vid. this was on an older version too, so I don't know if it's been fixed or not)

**Comment by Clientastisch** [comment]
The 2nd video is outdated. This check was removed in version 0.9977. This is 4 build behind

**Comment by Jakaboii** [comment]
OK, the second video is old.
But what about the 1st video?

**Comment by Clientastisch** [comment]
This should be fixed in version 0.9979 which will be available soon
