### ISSUE TITLE
Bug Report | NetFrequence Type A

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#85]
What type of bug you want to report? Describe it here
if you disable kicks for NetFrequence Type A and use timer it will still kick you

When the bug occurrs?
if you disable kicks for NetFrequence Type A and use timer it will still kick you

Cardinal Version: 0.9978
Spigot Version: 1.8.8

Attached Files
cancer

**Comment by Clientastisch** [comment]
I already noticed that. It'll be fixed in version 0.9979
