### ISSUE TITLE
Feature Request | Checks Cancelling Hits

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#86]
What features would you like added? Describe them here
Remove BlockHit Type A cancelling hits because its easier for people to make it a autoblock bypass when it doesn't cancel if there on a server Remove Hitbox Type A And Bs cancelling in hits cause it makes it easier to figure out what doesn't work and what works on some servers that use cardinal same with noswing type a

**Comment by Clientastisch** [comment]
Okay, I'll add a punishment type for those who want such an action

**Comment by Clientastisch** [comment]
This will be available in version 0.9979
