### ISSUE TITLE
Bypass | wallclimb

### ISSUE THREAD

**Issue by Jirka77777** [Clientastisch/Cardinal-Anticheat#87]
**Hack Client: LiquidBounce latest
**Hacking Type: WallClimb
**Link To Hacked Client:
You know.

**Cardinal Version: latest
**Spigot Version: 1.8.8-R0.1 with some custom changes

**Attached Video (Required)**
https://www.youtube.com/watch?v=fdw60_AEVIo

**Comment by Clientastisch** [comment]
It'll be detected by spider check but it is currently force disabled
