### ISSUE TITLE
Feature Request | Bungee Support

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#88]
**What features would you like added? Describe them here**
It'd be nice if the AntiCheat had a Bungeecord plugin in the .zip file

It would sync all the plugin messages and list the server the event is happening on (eg: someone is hacking on kitpvp, and I'm on survival. The plugin would send the alert to staff on survival & on kitpvp)

**Comment by Clientastisch** [comment]
Has been made by a user and is available in **#community-addons**
