### ISSUE TITLE
Bug Report | Spelling Mistake

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#89]
**What type of bug you want to report? Describe it here**
In Config.yml, it says `secounds` instead of `seconds` and the seconds placeholder is `%secounds%` instad of `%seconds%`

**When the bug occurrs?**
In the Config.yml file

**Cardinal Version:** 0.9981
**Spigot Version:** Paper 1.8.8 Latest Release

**Attached Files**
None

**Comment by Clientastisch** [comment]
Because I'm not english xd... It will be fixed in version 0.9982 though
