### ISSUE TITLE
Feature Request | Update the Spigot title

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#90]
**What features would you like added? Describe them here**
It isn't a big deal, but you might get more people using the AntiCheat if the title said 1.8 - 1.13.x or something, instead of just 1.8

**Comment by Clientastisch** [comment]
The Anticheat is made for 1.8.
Multiversion is just a nice extra but I don't truly try to fix cheats that are made versions higher than 1.8.
Futhermore most clients are made for 1.8 because most big servers are for 1.8 and higher
