### ISSUE TITLE
False Positive | Step Type A 

### ISSUE THREAD

**Issue by KlepMox** [Clientastisch/Cardinal-Anticheat#93]
**How do you trigger the false positive? Describe it here**
  It happens a few times, more when you jump water.

**Verbose Message**
  idk

**Cardinal Version: Lastest
**Spigot Version: 1.8.8 [Lastest]

**Attached Video  (Required)**
   https://youtu.be/kRhA49Xq-rI

**Comment by Clientastisch** [comment]
It was just an experimental check and currently force disabled
