### ISSUE TITLE
Spigot | Classloader issue ?

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#94]
**What type of bug you want to report? Describe it here**
NetFrequence Type A

**When the bug occurrs?**
When I logged into my spigot server through bungeecord
This only happened once though, when I relogged it was fine

**Cardinal Version:** 0.9981
**Spigot Version:** Paper 1.8.8 latest

**Attached Files**
https://hatebin.com/secjfkdqhv

**Comment by Clientastisch** [comment]
This isn't a NetFrequence Type A issue
And if all worked finde after relogging, where is the issue.
Sometimes the classloader from spigot just sucks, for instance you sure know the ClassNotFoundException

**Comment by Jakaboii** [comment]
Oh, OK
