### ISSUE TITLE
Feature Request | Prefix

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#95]
**What features would you like added? Describe them here**
An option to change the prefix of the anticheat
eg:
`prefix: '&4&lCAC'`

It'd be a nice feature to have, even though it doesn't make much of a difference. Plus most anticheats have this feature

**Comment by Clientastisch** [comment]
Nope, sorry but I don't want to make the prefix editable.
What's wrong with keeping the prefix CAC, only stuffs can see it anyway,...

Making the prefix editable makes it easy to pretend that it's your anticheat which it's not, where is my credit there ?
