### ISSUE TITLE
Bug Report | Paper 1.13.2

### ISSUE THREAD

**Issue by Jakaboii** [Clientastisch/Cardinal-Anticheat#96]
**What type of bug you want to report? Describe it here**
When you try to use Paper 1.13.2 the plugin just disables itself when someone joins
this doesn't happen on another paper version

**When the bug occurrs?**
When I join my Paper 1.13.2 server

**Cardinal Version:** Latest
**Spigot Version:** Paper 1.13.2 (latest release)

**Attached Files**
https://hatebin.com/dbnyzqpccj

**Comment by Clientastisch** [comment]
I guess I already told you, that paper has nothing to do with spigot.
I'm not sure if I'll fix this issue because it does work on spigot 1.13...
