### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by enqiaoshi2** [Clientastisch/Cardinal-Anticheat#97]
Hello CAC owner, some questions I want to support.
Why I cant install CAC anti-cheat. console said "Unsupported spigot modifications, please download a official spigot release" Idk why. Reply pls. My server is spigot.

**Comment by Clientastisch** [comment]
It's exactly what it says,
Cardinal can't locate fields because of some changes which are cause by an "unsupported modification" or because the server is running a version higher than 1.13.1

**Comment by enqiaoshi2** [comment]
But my server version is 1.11?
