### ISSUE TITLE
False Positive | Aim Assist and Kill Aura

### ISSUE THREAD

**Issue by KlepMox** [Clientastisch/Cardinal-Anticheat#98]
**How do you trigger the false positive? Describe it here**
Idk

**Verbose Message**
False flag of Aim Assist and Kill Aura

**Cardinal Version: 0.9982
**Spigot Version: PaperSpigot 1.8.8

**Attached Video  (Required)**
https://www.youtube.com/watch?v=XCmdqRPxVbo

**Comment by Clientastisch** [comment]
There has been some difficulties while trying to reporduce this either...

**Comment by Clientastisch** [comment]
KillAura seems to be because of PvPLounge Client, AimAssist Type B has been fixed in version 0.9983
