### ISSUE TITLE
False Positive | NoSlowDown

### ISSUE THREAD

**Issue by KlepMox** [Clientastisch/Cardinal-Anticheat#99]
**How do you trigger the false positive? Describe it here**
idk

**Verbose Message**
Blockhit bug

**Cardinal Version: 0.9982
**Spigot Version: PaperSpigot 1.8.8

**Attached Video  (Required)**
https://www.youtube.com/watch?v=tthv3tV0a80

**Comment by Clientastisch** [comment]
There has been some problems trying to reproduce this with default vanilla.
Could you try it without modified minecraft once ?

**Comment by KlepMox** [comment]
> Ha habido algunos problemas al intentar reproducir esto con la vainilla predeterminada.
> ¿Podrías probarlo sin modificar Minecraft una vez?
Try on mc vanilla?

**Comment by Clientastisch** [comment]
mc vanilla yes... ??

**Comment by KlepMox** [comment]
> 
> 
> mc vanilla yes... ??

i will try no mc vanilla

**Comment by KlepMox** [comment]
> 
> 
> mc vanilla yes... ??

https://www.youtube.com/watch?v=9KfBuFr8cDk

Only aim assist on Vanilla
Blockhit in vanilla is impossible

**Comment by Clientastisch** [comment]
AimAssist Type B will be fixed in version 0.9983
